### ISSUE TITLE
Can't Author Tabs, carousal and accordion Perfectly 

### ISSUE THREAD

**Issue by rohanpratapsingh99** [adobe/aem-guides-wknd#379] opened 2022-09-19 19:57 UTC
### Expected Behaviour
Tab should add one container in the dialog, if we add one container in itself

### Actual Behaviour
1. Firstly It is adding a tab container directly to the page
2. Pair of containers is getting added whenever we add more than 1 container in tabs

#### Steps to Reproduce
1. Author tabs 
2. Add container to the tab (1st issue it will not show in dialog). We have to click on save and reauthor the dialog to view
3. Add one more container (2nd issue it will not show in the dialog, as well as two containers, will be added to the page)
In total there should be 2 new containers loaded on the page but I am getting 3 containers, similarly, If I add one more container in the tab, on page 2 new container will be added

Concludingly
We have added the container 3 times but on the page, it is loading 5 containers. (Please don't consider 2 default container in this total)

#### Platform and Version
Adobe Experience Manager (2022.9.8630.20220905T184657Z)
core.wcm.components.content-2.19.0

**Issue 1**
![image](https://user-images.githubusercontent.com/46476795/191102012-8268ef05-ad25-4cd7-b668-6c4c24ac1c7d.png)

**Issue 2**
![Capture](https://user-images.githubusercontent.com/46476795/191105186-cbc35e4f-8362-4464-84df-30ee18bd6f21.PNG)

**Comment by SachinMali** [comment] 2022-11-10 21:12
@rohanpratapsingh99 I could not reproduce it on AEM RELEASE: 2022.10.9398.20221020T071514Z and WKND Main branch. 

Can you please try again..

**Comment by SachinMali** [comment] 2023-01-09 14:53
Closing this because no further updates, please re-open if needed.

**Closed by SachinMali** 2023-01-09 14:53 UTC
Labels: question
