### ISSUE TITLE
WKND pages missing grids in "View as Published" mode on Author

### ISSUE THREAD

**Issue by sharadkap** [adobe/aem-guides-wknd#6] opened 2019-06-06 09:57 UTC
Steps:

1. Navigate to any page in WKND --> http://localhost:4502/editor.html/content/wknd/en/restaurants/best-tacos-in-the-city.html
2. Check page in Preview mode (also in Edit Mode) 
![FireShot Capture 001 - Best Tacos in the City - localhost](https://user-images.githubusercontent.com/5682531/59024256-dfa23e00-8894-11e9-9c16-54be0a2c097c.png)

3. Click on settings and "View as Published" 
<img width="1680" alt="Screen Shot 2019-06-06 at 7 45 17 pm" src="https://user-images.githubusercontent.com/5682531/59024154-a4077400-8894-11e9-810f-bb02591c66f3.png">
4. Now see how the page looks like. It happens on all the pages. 

![FireShot Capture 002 - Best Tacos in the City - localhost](https://user-images.githubusercontent.com/5682531/59024388-2859f700-8895-11e9-844e-1e990fe53ff7.jpg)

AEM Version - 6.4.2 
AEM Core - 2.4.2

**Comment by godanny86** [comment] 2019-06-12 15:05
hi @sharadkap is there anything in the AEM error log: `<aem-install-directory>/crx-quickstart/logs/error.log`?

Also do you see any errors in the browser? Perhaps a LESS compiler error in the generated css?

**Comment by sharadkap** [comment] 2019-06-12 20:19
Hey @godanny86 

Thanks for checking. No there is no error anywhere. I checked the LESS compilation and error log and both show nothing suspicious for me. Are you able to replicate? This happens on a vanilla AEM as well with only WKDN installed. 

This is a blocking one of my own project releases as we needed the same and both of ours and WKND templates have the same issue. 

Any help would be great. 

Thanks!

**Comment by godanny86** [comment] 2019-06-12 20:21
Hi @sharadkap I will try to reproduce. Just to confirm your environment is:
AEM Version - 6.4.2
AEM Core - 2.4.2
?

**Comment by sharadkap** [comment] 2019-06-12 20:23
Sorry it is 
AEM 6.4.4 and Core 2.4.2

**Comment by godanny86** [comment] 2019-06-12 23:16
Actually do you mean Core Components 2.3.2 or 2.4.0? there has not been a Core Components 2.4.2 AFAIK: https://github.com/adobe/aem-core-wcm-components/releases

**Comment by sharadkap** [comment] 2019-06-12 23:29
Yes, sorry again 😐. Its 2.3.2 AEM core. @godanny86

**Comment by godanny86** [comment] 2019-06-13 00:24
hi @sharadkap, sorry I was not able to reproduce the issue. 

I have AEM 6.4 + SP4 installed:
![image](https://user-images.githubusercontent.com/8974514/59394940-7c058e00-8d36-11e9-9a5e-bd2a0b8f126a.png)

And I have used the version of the WKND project that installs 2.3.2: https://github.com/adobe/aem-guides-wknd/releases/tag/archetype-18
 *note this is not the latest version*
![image](https://user-images.githubusercontent.com/8974514/59394918-642e0a00-8d36-11e9-9cca-1f7c64b182f7.png)

if you check http://locahost:4502/etc.clientlibs/wknd/clientlibs/clientlib-base.css and search for `error` do you see anything?

**Comment by sharadkap** [comment] 2019-06-13 02:46
Thanks @godanny86 
I will check this sooner and will let you know. 

I will try with AEM core 2.3.0 (the embed one) and uninstall the 2.3.2. 

Do you want to keep this open until then?

**Comment by sharadkap** [comment] 2019-06-13 04:25
Hey @godanny86 - no error on that file.
http://localhost:4502/etc.clientlibs/wknd/clientlibs/clientlib-base.css 
Issue still persists. Tried on Incognito, Private, clear cache browsers. 

https://file.io/WEinI8 the css file that is generated.

**Comment by godanny86** [comment] 2019-06-17 17:41
@sharadkap is the HTML classes changing? if there are no issues with the CSS then that is the next place to look...

**Comment by godanny86** [comment] 2019-06-27 16:58
@sharadkap closing this for now. If you have more info about this unexpected behavior feel free to open...

**Closed by godanny86** 2019-06-27 16:58 UTC
Labels: More Info Needed, bug
