### ISSUE TITLE
Unable to see content in pages in WKND sites & WE retail. 

### ISSUE THREAD

**Issue by Rojkumar2306** [adobe/aem-guides-wknd#340] opened 2022-04-20 09:30 UTC
after installing bundles,  in http://localhost:4502/system/console/bundles "wknd-sites" & "We-Retail" are showing as installed instead of active. Unable to see content on edit pages.

**Comment by godanny86** [comment] 2022-04-20 14:43
Hi @Rojkumar2306 a few follow ups:
1. what version of AEM are you using, is this 6.5? 
2. Also what Service Pack do you have? 
3. What version of WKND did you install? There is a `classic` variation that is intended to be installed on 6.5 environments

**Comment by Rojkumar2306** [comment] 2022-04-21 05:02
> Hi @Rojkumar2306 a few follow ups:
> 
> 1. what version of AEM are you using, is this 6.5?
> 2. Also what Service Pack do you have?
> 3. What version of WKND did you install? There is a `classic` variation that is intended to be installed on 6.5 environments

Yes i am using 6.5. Whenever i am trying to extract zip files(aem-guides-wknd-main.zip) i am getting errors like error 0x80010135. path too long.
and... could u please clarify that 1.i should install "aem- guides-wknd-all-1.1.0.-classic.zip" and then i should install "aem-guides-wknd-main.zip".
thats what i am doing..please guide me gng in wrng direction.
******my maven version 3.8.5
******aem 6.5 provided by my organization which i am wrkng now. 

help me out plssss...its killing my time
<img width="343" alt="githuberror" src="https://user-images.githubusercontent.com/89206593/164375672-f251b614-f2ef-48ee-95b2-5cd11585fa48.png">

**Comment by Rojkumar2306** [comment] 2022-04-21 05:42
i tried to validate the classic package. 
This is what i got..
if i proceed to install anyway, We-retail & wknd-sites wont be active.
what should i do now???????????

Validate Package: [/etc/packages/com.adobe.aem.guides/aem-guides-wknd.all-1.1.0.zip]()
Thu Apr 21 2022 11:06:56 GMT+0530 (India Standard Time)

Validating content package

5 unsatisfied OSGi package imports in 2 bundles.
1. Unsatisfied package import com.day.cq.wcm.api-[1.28.0,2.0.0) in bundle aem-guides-wknd.core-1.1.0 present at aem-guides-wknd.all-1.1.0.zip/jcr_root/apps/wknd-packages/application/install/aem-guides-wknd.core-1.1.0.jar
2. Unsatisfied package import com.day.cq.wcm.api-[1.28.0,2.0.0) in bundle com.adobe.cq.core.wcm.components.core-2.17.12 present at aem-guides-wknd.all-1.1.0.zip/jcr_root/apps/wknd-vendor-packages/application/install/core.wcm.components.core-2.17.12.jar
3. Unsatisfied package import org.apache.sling.api.servlets-[2.3.0,3.0.0) in bundle com.adobe.cq.core.wcm.components.core-2.17.12 present at aem-guides-wknd.all-1.1.0.zip/jcr_root/apps/wknd-vendor-packages/application/install/core.wcm.components.core-2.17.12.jar
4. Unsatisfied package import org.apache.commons.lang3-[3.9.0,4.0.0) in bundle aem-guides-wknd.core-1.1.0 present at aem-guides-wknd.all-1.1.0.zip/jcr_root/apps/wknd-packages/application/install/aem-guides-wknd.core-1.1.0.jar
5. Unsatisfied package import com.fasterxml.jackson.annotation-[2.10.0,3.0.0) in bundle aem-guides-wknd.core-1.1.0 present at aem-guides-wknd.all-1.1.0.zip/jcr_root/apps/wknd-packages/application/install/aem-guides-wknd.core-1.1.0.jar

Following 2 bundles will go from 'Active' to 'Installed' state if you install this content package.
1. aem-guides-wknd.core-1.1.0
2. com.adobe.cq.core.wcm.components.core-2.17.12



5 unsatisfied OSGi package imports. No overlay rebase warnings. No ACL warnings.

Package validated in 1ms.

**Comment by mthomas46** [comment] 2022-05-04 21:39
running into the same issue hopefully this helps. This is the console log and it's showing that is's unable to resolve a few bundles.

<img width="1612" alt="Screen Shot 2022-05-03 at 4 41 09 PM" src="https://user-images.githubusercontent.com/2440190/166830043-0bbbdac0-74b8-4f36-aef8-f5e9a9b4b53a.png">

**Comment by godanny86** [comment] 2022-05-05 00:43
Thanks @mthomas46. Apologies @Rojkumar2306 I didn't see your response. I think the issues are related to the lack of Service Pack installed on the target 6.5 environments.

The latest release of WKND for AEM 6.5 **requires** a minimum Service Pack 10 to be installed. If this is a fresh environment install the latest service pack which is 12:

1. Start a fresh instance of AEM 6.5
2. Download and install [Service Pack 12](https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?package=/content/software-distribution/en/details.html/content/dam/aem/public/adobe/packages/cq650/servicepack/aem-service-pkg-6.5.12.0.zip) via [CRX Package Manager](http://localhost:4502/crx/packmgr/index.jsp)
3. Download and install the **classic** compiled version of WKND [aem-guides-wknd.all-1.1.0-classic.zip](https://github.com/adobe/aem-guides-wknd/releases/download/aem-guides-wknd-1.1.0/aem-guides-wknd.all-1.1.0-classic.zip) using package manager. There is no need to unzip this artifact as it is the compiled version.

for @mthomas46 it looks like you generated a new project using the [AEM Project Archetype](https://github.com/adobe/aem-project-archetype)? I'm not sure if that is the case but I see that the version you have is 0.0.1-SNAPSHOT. If this is the case ensure that when generating the project you specify the version of AEM you are using. So for Service Pack 10 you would generate a new project like so:

```
mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
    -D archetypeGroupId=com.adobe.aem \
    -D archetypeArtifactId=aem-project-archetype \
    -D archetypeVersion=35 \
    -D appTitle="WKND Sites Project" \
    -D appId="wknd" \
    -D groupId="com.adobe.aem.guides" \
    -D artifactId="aem-guides-wknd" \
    -D package="com.adobe.aem.guides.wknd" \
    -D version="0.0.1-SNAPSHOT" \
    -D aemVersion="6.5.10"
```

And also ensure that Service Pack 10 is installed on the target AEM 6.5 environment.

**Comment by mthomas46** [comment] 2022-05-05 17:06
@godanny86 so i copied the project repo from the component-basics-start branch. It seems like the documentation or branch for the tutorial is a little out of date. i'm using service pack 8 so thats probably the reason, i'll try grabbing 12.

**Comment by godanny86** [comment] 2022-05-05 17:17
hey @mthomas46 the tutorial specifies 6.5.10 as a minimum version: https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-wknd-tutorial-develop/project-archetype/overview.html?lang=en#local-dev-environment. Is there another place where you see SP 8 referenced?

**Comment by mthomas46** [comment] 2022-05-05 17:22
@godanny86 the link to the service pack does not seem to work with a personal account. I'll have to ask a coworker to get it for me. thanks for the help.

**Comment by mthomas46** [comment] 2022-05-09 23:02
<img width="1609" alt="Screen Shot 2022-05-09 at 6 00 19 PM" src="https://user-images.githubusercontent.com/2440190/167512335-1fd460c2-8015-4170-8cfc-e4e996b9df66.png">

I've upgraded to SP12 and it still is unable to resolve the following bundles on a fresh install
org.apache.sling.api.request,version=[2.6,3) -- Cannot be resolved
org.apache.sling.api.resource,version=[2.13,3) -- Cannot be resolved

**Comment by godanny86** [comment] 2022-05-10 01:53
Thanks @mthomas46 i'll try and reproduce on my end. Remind me, what branch are you working with, is it: https://github.com/adobe/aem-guides-wknd/tree/tutorial/component-basics-start ?

**Comment by mthomas46** [comment] 2022-05-10 16:11
> Thanks @mthomas46 i'll try and reproduce on my end. Remind me, what branch are you working with, is it: https://github.com/adobe/aem-guides-wknd/tree/tutorial/component-basics-start ?

component basic start

**Comment by mthomas46** [comment] 2022-05-13 18:15
@godanny86  any update on this?

**Comment by godanny86** [comment] 2022-05-13 18:42
Hey @mthomas46 i wasn't able to reproduce it. Are you using the `-Pclassic` profile to build?

```
mvn clean install -PautoInstallSinglePackage -Pclassic
```

**Comment by mthomas46** [comment] 2022-05-13 21:16
> Hey @mthomas46 i wasn't able to reproduce it. Are you using the `-Pclassic` profile to build?
> 
> ```
> mvn clean install -PautoInstallSinglePackage -Pclassic
> ```

i'll give that a shot

**Comment by SachinMali** [comment] 2022-09-01 21:57
Closing this as because of no further updates, if the issue persists please reopen.

**Closed by SachinMali** 2022-09-01 21:57 UTC
Labels: More Info Needed
